### ISSUE TITLE
SVG animateTransform tag missing

### ISSUE THREAD

**Issue by sbala69gmail** [jannicz/ng-svg-icon-sprite#36]
Animation tag was missed in `<svg-icon-sprite [src]="'spin'" ></svg-icon-sprite>`.

The sprite SVG output had **animateTransform**. But using "svg-icon-sprite", the **animateTransform** tag was missing. Transform animation missing and show single snap image-only,

I have download from internet and used for render, transform missing

```
<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: none; display: block; shape-rendering: auto;" width="200px" height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
<circle cx="50" cy="50" r="32" stroke-width="8" stroke="#fe718d" stroke-dasharray="50.26548245743669 50.26548245743669" fill="none" stroke-linecap="round" transform="rotate(311.837 50 50)">
  <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" keyTimes="0;1" values="0 50 50;360 50 50"></animateTransform>
</circle></svg>
```

Plz, suggest how to use animate SVG to convert sprite. 
Thanks.

**Comment by jannicz** [comment]
As I understand you correct, running the 'generate:sprite' npm task removes the `animateTransform` tag from your sprite file containing the symbols, correct?

**Comment by sbala69gmail** [comment]
No. `<svg-icon-sprite [src]="'spin'" ></svg-icon-sprite>` While access the sprite file and render time only the was tag removed.

**Comment by sbala69gmail** [comment]
Anybody have a solution for this issue: https://stackoverflow.com/questions/46981649/svg-animatetransform-tag-is-lost-when-using-svg-use

**Comment by gasfab999** [comment]
@sbala69gmail for sure it is already a bit to late, however if someone else comes across this: Svg animations don't work here as the sprite is loaded from an external file. This is not caused by this lib, this is how the browsers behave together with the svg `use`. In order to fix it you would need to inline/embed the sprite in e.g. you index.html file. I found a good example here where you can easily check the DOM element in the browser [http://bl.ocks.org/bertspaan/6182774](http://bl.ocks.org/bertspaan/6182774). You can see there that also just with plain HTML the `animateTransform` nodes got removed by the browser.

An option for that would be to use in addition [svg-sprite-loader](https://github.com/JetBrains/svg-sprite-loader) to add the svg icons through a hidden node to the current document and then you can set the path for this ng lib to an empty string (`IconSpriteModule.forRoot({ path: '' })`

**Comment by jannicz** [comment]
@gasfab999 thank you for clarifying this issue and providing an example. I consider the issue closed.
