### ISSUE TITLE
[MacOS] bug: env: node\r: No such file or directory

### ISSUE THREAD

**Issue by AndriiTsok** [jannicz/ng-svg-icon-sprite#42]
There is a bug with the latest version of svg2sprite-cli https://github.com/mrmlnc/svg2sprite-cli/issues/4
Sprite compilation doesn't work on Mac.

CC @ihor-zahnybida

**Comment by jannicz** [comment]
I cannot reproduce what you experience. On my Mac it runs like it should. But you can always call the script directly from your node_modules via:
`node node_modules/svg2sprite-cli/out/cli ./src/icons ./src/sprites/sprite.svg`

If you don't provide any proof otherwise i will close this issue by Tuesday.

**Comment by jannicz** [comment]
Thank you for using the lib, good luck with your project! Feel free to open new issues if you encounter any
