### ISSUE TITLE
How to change fill and storke properties using angular input

### ISSUE THREAD

**Issue by st-clair-clarke** [jannicz/ng-svg-icon-sprite#47]
Hi, Great package. Congratulations. I love it.

I am trying to change the fill and stroke of ng-svg-icon-sprite as in the instructions, but getting nowhere. Given the component below, what do I need to do to be able to change the fill and stroke input dynamically:

```@Component({
  selector: 'pim-ng-svg-icon-sprite',
  template: `
    <div class="svg-scale">
      <svg-icon-sprite
        id="x"
        [style]="style"
        [src]="icon"
        [viewBox]="viewBox"
        [width]="width"
      ></svg-icon-sprite>
    </div>
  `,
  styles: [
    `
      .svg-scale {
        /*Scale down by 50%*/
        transform: scale(1);
      }

     <!-- does not work
      ::ng-deep #x {{
        use {
          fill: orange;
          stroke: black;
        }
      }
     -->
    `,
  ],
})
export class NgSvgIconSpriteComponentWrapper {
@input() fill = 'red'
@Input stroke = 'blue
  @Input() icon = 'fox'
  @Input() scale = 0.5
  @Input() style = 'color: #ab3030;'
  @Input() width = '24px'
  viewBox = '0 0 ${width} ${width}'
}```

**Comment by jannicz** [comment]
Hi @st-clair-clarke,

i am glad that you like the lib. In order to apply CSS to your inline SVG, you will have to export the icon in the right way. The exported SVG **must not** contain any fill and stroke rules (inside its markup), otherwise inline styles will win over CSS styles. I recommend stripping the properties [automatically](https://github.com/jannicz/ng-svg-icon-sprite#step-1-generate-the-sprite) or via hand (by deleting only the fill/stroke rules from the SVG paths you want to overwrite by CSS). Have a look at this codepen https://codepen.io/roblevin/pen/raBZvv that shows the possibilities.

As this is not a problem with the lib itself, I will close this Issue by tomorrow (if I do not hear otherwise).

Regards

jan

**Comment by st-clair-clarke** [comment]
Thanks for your reply. The fill and stroke have been stripped. What I am requesting your help about is the usage of ::ng-deep. Could you please tweak my example above to demonstrate its usage.

**Comment by jannicz** [comment]
Yes, use either `[attr.style]="style"` or simply `style="style"` without the brackets. It is not an component input but a general style for the node. Another tip: do not use ids (#) for styling purposes - use classes. Can be closed?

**Comment by jannicz** [comment]
I update the demo code example accordingly, see https://jannicz.github.io/ng-svg-icon-sprite/

Thank you for the improvement hint!
