### ISSUE TITLE
Problem with Angular testing 

### ISSUE THREAD

**Issue by kristiyan-velkov** [jannicz/ng-svg-icon-sprite#54]
Hello, I follow the instructions but is have a problem when trying to config the @NgModule for the specific test. 

ERROR: 'NG0304: 'svg-icon-sprite' is not a known element:
1. If 'svg-icon-sprite' is an Angular component, then verify that it is part of this module.
2. If 'svg-icon-sprite' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.'

Note: Not working to import the IconSpriteModule or IconSpriteComponent.

Please, write me for more info. 

Best regards

**Comment by jannicz** [comment]
What kind of test are you writing? Probably you will have to add the **svg-icon-sprite** [module](https://github.com/jannicz/ng-svg-icon-sprite/blob/master/projects/icon-sprite/src/lib/icon-sprite.module.ts) or its [component](https://github.com/jannicz/ng-svg-icon-sprite/blob/master/projects/icon-sprite/src/lib/icon-sprite.component.ts) to the declarations of each test or all tests, i.e.

`declarations: [IconSpriteComponent] `

or

`imports: [IconSpriteModule]`

You can read https://molily.de/testing-angular/testing-modules/ - this does not sound like an error with the library itself. If I don't hear otherwise I will close this issue until end of this week.

**Comment by kristiyan-velkov** [comment]
Hello @jannicz , thank you for your answer. 

Look please at my comment what I wrote. 

"Note: Not working to import the IconSpriteModule or IconSpriteComponent.


Best regards

**Comment by saharheidarpour** [comment]
If you are not testing the interaction between parent and child components you can ignore the child components in the template .You can also use "NO_ERRORS_SCHEMA"
```

 TestBed.configureTestingModule({
    declarations: [
        ...
    ],
    schemas: [NO_ERRORS_SCHEMA]
```

**Comment by kristiyan-velkov** [comment]
Hello, is not good solution to use not error schema. I want to config my tests properly for that reason I want to put the child component. I wrote unit tests but the test doesn't have mater. Is have some problem with component. Try pls to use the newest version of Angular and the npm package who you wrote and you will see the issue. If you have more questions or you want to show you directly pls ping me, I will help. Chears

**Comment by lin1010** [comment]
> If you are not testing the interaction between parent and child components you can ignore the child components in the template .You can also use "NO_ERRORS_SCHEMA"
> 
> ```
> 
>  TestBed.configureTestingModule({
>     declarations: [
>         ...
>     ],
>     schemas: [NO_ERRORS_SCHEMA]
> ```

Hi, I have the same issue. It works in angular 10, but when I upgrade to angular 11, it doesn't work.

**Comment by jannicz** [comment]
@christiyan14, @lin1010, I created a code sandbox with Angular 11 and a simple unit test. Could you maybe fork this and add your configuration that is causing the issue (so I can reproduce it).
https://codesandbox.io/s/thirsty-hawking-i03mj?file=/src/app/app.module.ts

Thanks

**Comment by jannicz** [comment]
Will close this one as no answer given. Thanks for using!
