### ISSUE TITLE
Error when building a docker project that has the ng-svg-icon-sprite package

### ISSUE THREAD

**Issue by loozmax** [jannicz/ng-svg-icon-sprite#80]
Hello. We use ng-svg-icon-sprite in our project. There was a problem that the docker container stopped building. When I run the docker build command, I get an "Cant import the named export from non Ecmascript module (only default export is available)" error. We have version 11 of Angular. There are suspicions that the problem is with dependencies. Could you suggest what can be done? Maybe we need to update Angular?

Update: We have been using the package for 2 years now, but the error appeared a couple of days ago
"ng-svg-icon-sprite": "^1.10.0",

![Clipboard - 24 июня 2022 г , 17_04](https://user-images.githubusercontent.com/62829571/175770635-17a6ff6a-9dee-4357-9561-77cf3c90b2b9.png)

**Comment by jannicz** [comment]
Hello @loozmax, thanks for asking this question. The reason is that using ^ in the dependency version will pull the latest 1.x version (what is currently 1.2 for Angular 14). What you want, is just to upgrade the 1.1.x version of ng-svg-icon-sprite. This you can achieve by writing:
`"ng-svg-icon-sprite": "~1.10.0"`

See https://stackoverflow.com/questions/22343224/whats-the-difference-between-tilde-and-caret-in-package-json

Tell me if that worked for you

**Comment by loozmax** [comment]
Working perfectly! Thanks so much
