### ISSUE TITLE
Angular 15+ requires use of --legacy-peer-deps when installing

### ISSUE THREAD

**Issue by fslone** [jannicz/ng-svg-icon-sprite#92]
As of Angular 15 our project has had to use `npm install --legacy-peer-deps` when installing because this package is using outdated dependencies. Do you plan on updating the project to support Angular 15 & 16 in the future? Thanks in advance.

**Comment by jannicz** [comment]
Thanks for the information. Yes, i am planning to create an update this summer!

**Comment by victorbjorn** [comment]
+1 It would be nice.

**Comment by sergii-hq** [comment]
Any news regarding update?

**Comment by jannicz** [comment]
The above issues should be solved by the next release in #93

**Comment by jannicz** [comment]
@sergii-hq @victorbjorn @finleywilliamsonV Please check whether all described compatibility problems are now solved with new new module [1.13.2](https://www.npmjs.com/package/ng-svg-icon-sprite)

Thanks for the patience. I know it took very long. Next time i will do the upgrade quicker. Apologies to all people that had problems because of that!!!

**Comment by jannicz** [comment]
Thanks for using. I will now close this issue as no problems appeared :-D
